from fastapi import APIRouter

router = APIRouter()

CITY_DATA = [
    {
        "name": "Austin, TX", "tech_score": 95, "growth_label": "Explosive",
        "total_tech_jobs": 8400, "ai_jobs": 1240, "finance_tech_jobs": 1100,
        "avg_salary": 132000, "startup_activity": "Very High",
        "top_industries": ["AI & Machine Learning", "Semiconductors", "Fintech", "Cloud Computing"],
        "summary": "Austin has emerged as the dominant alternative to Silicon Valley, drawing Tesla, Apple, and Google with its no-income-tax environment and lower cost of living. The city leads the nation in tech job growth rate and venture capital inflow relative to its size, with particular strength in semiconductor design and AI infrastructure companies.",
        "cost_of_living": {"index": 95, "note": "Slightly below US average. Rising fast due to migration from CA and NY.", "avg_rent_1br": 1650, "avg_home_price": 540000},
        "weather": {"description": "Hot summers, mild winters, sunny nearly year-round.", "avg_summer": "95°F (35°C)", "avg_winter": "52°F (11°C)", "sunny_days": 228},
        "colleges": ["University of Texas at Austin", "St. Edward's University", "Austin Community College"],
        "major_companies": ["Tesla", "Apple", "Google", "Meta", "Oracle", "Dell Technologies", "IBM", "Indeed"]
    },
    {
        "name": "Seattle, WA", "tech_score": 92, "growth_label": "Strong",
        "total_tech_jobs": 14200, "ai_jobs": 2800, "finance_tech_jobs": 1400,
        "avg_salary": 158000, "startup_activity": "Very High",
        "top_industries": ["Cloud Computing", "E-Commerce", "AI Research", "Aerospace Tech"],
        "summary": "Seattle remains one of the highest-paying tech markets in the country, anchored by Amazon and Microsoft headquarters. The city has a mature, deep talent pool with particularly strong cloud infrastructure, AI research, and enterprise software ecosystems. Amazon's AWS and Microsoft Azure both operate significant research divisions here.",
        "cost_of_living": {"index": 118, "note": "Above US average. High salaries offset higher costs but housing is competitive.", "avg_rent_1br": 2100, "avg_home_price": 720000},
        "weather": {"description": "Mild, rainy winters. Warm, dry summers. Overcast much of the year.", "avg_summer": "75°F (24°C)", "avg_winter": "40°F (4°C)", "sunny_days": 152},
        "colleges": ["University of Washington", "Seattle University", "Bellevue College"],
        "major_companies": ["Amazon (HQ)", "Microsoft (HQ)", "Boeing", "Expedia", "Zillow", "Redfin", "Convoy"]
    },
    {
        "name": "Dallas, TX", "tech_score": 91, "growth_label": "Strong",
        "total_tech_jobs": 9100, "ai_jobs": 1450, "finance_tech_jobs": 2200,
        "avg_salary": 118000, "startup_activity": "High",
        "top_industries": ["Fintech", "Telecom", "AI & Data", "Cybersecurity"],
        "summary": "Dallas is the largest fintech hub in the southern United States, benefiting from AT&T's global headquarters, Goldman Sachs and JPMorgan's expanding tech campuses, and a business-friendly regulatory environment. The city's financial services tech sector is outpacing national growth rates.",
        "cost_of_living": {"index": 101, "note": "Right at the US average. No state income tax.", "avg_rent_1br": 1520, "avg_home_price": 420000},
        "weather": {"description": "Very hot summers, mild winters. Occasional severe spring storms.", "avg_summer": "96°F (36°C)", "avg_winter": "45°F (7°C)", "sunny_days": 234},
        "colleges": ["SMU", "UT Dallas", "TCU", "University of North Texas"],
        "major_companies": ["AT&T", "Goldman Sachs", "JPMorgan Chase", "American Airlines", "Toyota North America", "Match Group"]
    },
    {
        "name": "Boston, MA", "tech_score": 90, "growth_label": "Strong",
        "total_tech_jobs": 11800, "ai_jobs": 2200, "finance_tech_jobs": 1900,
        "avg_salary": 148000, "startup_activity": "Very High",
        "top_industries": ["Biotech & Life Sciences", "AI Research", "Fintech", "Robotics"],
        "summary": "Boston is one of the world's premier biotech and life sciences hubs, driven by proximity to MIT, Harvard, and a dense concentration of research hospitals. The city also hosts a rapidly expanding AI research community, with major labs from Google, Microsoft, and numerous AI-native startups operating out of Kendall Square.",
        "cost_of_living": {"index": 122, "note": "Significantly above US average. One of the most expensive markets outside of NYC and SF.", "avg_rent_1br": 2800, "avg_home_price": 780000},
        "weather": {"description": "Cold snowy winters, warm summers, beautiful fall foliage.", "avg_summer": "82°F (28°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 200},
        "colleges": ["MIT", "Harvard University", "Northeastern University", "Boston University", "Tufts"],
        "major_companies": ["Wayfair", "HubSpot", "Moderna", "Biogen", "Fidelity Investments", "State Street", "Toast"]
    },
    {
        "name": "Chicago, IL", "tech_score": 88, "growth_label": "Strong",
        "total_tech_jobs": 10400, "ai_jobs": 1600, "finance_tech_jobs": 3100,
        "avg_salary": 124000, "startup_activity": "High",
        "top_industries": ["Fintech", "Trading & Finance", "Enterprise SaaS", "Logistics Tech"],
        "summary": "Chicago is the financial trading capital of the United States and is rapidly becoming a major fintech hub, with the Chicago Mercantile Exchange, CBOE, and a growing number of algorithmic trading and blockchain companies headquartered there. The city's enterprise SaaS ecosystem is also maturing quickly.",
        "cost_of_living": {"index": 107, "note": "Slightly above US average. High property taxes but strong salary compensation.", "avg_rent_1br": 1900, "avg_home_price": 330000},
        "weather": {"description": "Very cold winters with heavy snow. Hot humid summers. Windy year-round.", "avg_summer": "84°F (29°C)", "avg_winter": "26°F (-3°C)", "sunny_days": 189},
        "colleges": ["University of Chicago", "Northwestern University", "Illinois Institute of Technology", "DePaul"],
        "major_companies": ["Morningstar", "Groupon", "Outcome Health", "Tempus", "Relativity", "SPINS", "Coyote Logistics"]
    },
    {
        "name": "Raleigh, NC", "tech_score": 87, "growth_label": "Strong",
        "total_tech_jobs": 6200, "ai_jobs": 980, "finance_tech_jobs": 870,
        "avg_salary": 112000, "startup_activity": "High",
        "top_industries": ["Cybersecurity", "Biotech", "Software Engineering", "AI Research"],
        "summary": "Raleigh anchors the Research Triangle — one of the most research-dense corridors in the US — benefiting from NC State, Duke, and UNC Chapel Hill as major talent pipelines. The region has the highest concentration of PhD-level engineers outside of Boston and the Bay Area, making it ideal for deep tech and cybersecurity.",
        "cost_of_living": {"index": 93, "note": "Below US average. Excellent value for tech salaries vs. living costs.", "avg_rent_1br": 1450, "avg_home_price": 390000},
        "weather": {"description": "Four distinct seasons. Mild summers, cool winters, occasional light snow.", "avg_summer": "88°F (31°C)", "avg_winter": "40°F (4°C)", "sunny_days": 213},
        "colleges": ["NC State University", "Duke University", "UNC Chapel Hill"],
        "major_companies": ["Red Hat (IBM)", "Cisco", "SAS Institute", "Lenovo", "Epic Games", "Bandwidth"]
    },
    {
        "name": "Miami, FL", "tech_score": 86, "growth_label": "Explosive",
        "total_tech_jobs": 5800, "ai_jobs": 920, "finance_tech_jobs": 1700,
        "avg_salary": 108000, "startup_activity": "Very High",
        "top_industries": ["Fintech", "Crypto & Web3", "Latin America Tech", "Real Estate Tech"],
        "summary": "Miami has undergone one of the fastest tech ecosystem transformations of any US city, driven by the mayor's active tech recruitment, no state income tax, and its position as the financial gateway to Latin America. The city has become a hub for crypto, Web3, and fintech companies, with significant hedge fund and VC relocation from New York.",
        "cost_of_living": {"index": 112, "note": "Above US average and rising. Luxury real estate has pushed costs up significantly.", "avg_rent_1br": 2200, "avg_home_price": 580000},
        "weather": {"description": "Tropical. Hot and humid year-round. Hurricane season June-November.", "avg_summer": "90°F (32°C)", "avg_winter": "68°F (20°C)", "sunny_days": 248},
        "colleges": ["University of Miami", "Florida International University", "Miami Dade College"],
        "major_companies": ["Citadel", "Founders Fund", "Blockchain.com", "Pipe", "Kaseya", "Magic Leap"]
    },
    {
        "name": "Denver, CO", "tech_score": 85, "growth_label": "Strong",
        "total_tech_jobs": 5700, "ai_jobs": 870, "finance_tech_jobs": 950,
        "avg_salary": 119000, "startup_activity": "High",
        "top_industries": ["Aerospace Tech", "Cybersecurity", "SaaS", "Clean Energy Tech"],
        "summary": "Denver's tech growth is fueled by a combination of aerospace and defense contracts, government cybersecurity work, and a rapidly growing SaaS startup community. The city consistently ranks highly for quality of life among tech workers, contributing to strong talent retention.",
        "cost_of_living": {"index": 103, "note": "Slightly above US average. Higher housing offset by strong salaries.", "avg_rent_1br": 1720, "avg_home_price": 560000},
        "weather": {"description": "Mild summers, cold snowy winters. Over 300 sunny days per year.", "avg_summer": "85°F (29°C)", "avg_winter": "32°F (0°C)", "sunny_days": 300},
        "colleges": ["University of Denver", "CU Denver", "Colorado State University"],
        "major_companies": ["Lockheed Martin", "DISH Network", "Arrow Electronics", "Palantir", "Ping Identity"]
    },
    {
        "name": "Atlanta, GA", "tech_score": 83, "growth_label": "Rising",
        "total_tech_jobs": 5900, "ai_jobs": 910, "finance_tech_jobs": 1400,
        "avg_salary": 108000, "startup_activity": "High",
        "top_industries": ["Fintech", "Media Tech", "Cybersecurity", "Cloud"],
        "summary": "Atlanta has established itself as the fintech capital of the Southeast, processing more payment transactions annually than any US city outside of New York. Georgia Tech provides a world-class engineering pipeline, and the city's HBCU network — including Morehouse and Spelman — is increasingly producing tech talent.",
        "cost_of_living": {"index": 96, "note": "Slightly below US average. Traffic adds hidden time costs.", "avg_rent_1br": 1580, "avg_home_price": 380000},
        "weather": {"description": "Hot humid summers, mild winters. Rarely snows significantly.", "avg_summer": "89°F (32°C)", "avg_winter": "44°F (7°C)", "sunny_days": 216},
        "colleges": ["Georgia Tech", "Emory University", "Georgia State", "Morehouse", "Spelman"],
        "major_companies": ["NCR Voyix", "Cardlytics", "Cox Enterprises", "Delta Tech", "Home Depot HQ", "Salesloft"]
    },
    {
        "name": "Salt Lake City, UT", "tech_score": 82, "growth_label": "Explosive",
        "total_tech_jobs": 4900, "ai_jobs": 780, "finance_tech_jobs": 820,
        "avg_salary": 110000, "startup_activity": "Very High",
        "top_industries": ["SaaS", "Cybersecurity", "Fintech", "Health Tech"],
        "summary": "Silicon Slopes — the tech corridor stretching from Salt Lake City to Provo — is one of the fastest-growing tech ecosystems in the country on a per-capita basis. The region benefits from a young, highly educated workforce, low taxes, and a strong community of bootstrapped and venture-backed SaaS companies.",
        "cost_of_living": {"index": 96, "note": "Slightly below US average. Rising fast but still strong value.", "avg_rent_1br": 1480, "avg_home_price": 460000},
        "weather": {"description": "Cold snowy winters (world-class skiing), warm dry summers.", "avg_summer": "92°F (33°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 222},
        "colleges": ["University of Utah", "Brigham Young University", "Utah Valley University"],
        "major_companies": ["Adobe", "Qualtrics", "Domo", "Pluralsight", "Ancestry", "HealthEquity", "Vivint"]
    },
    {
        "name": "Charlotte, NC", "tech_score": 81, "growth_label": "Rising",
        "total_tech_jobs": 4800, "ai_jobs": 760, "finance_tech_jobs": 1800,
        "avg_salary": 104000, "startup_activity": "Medium",
        "top_industries": ["Banking Tech", "Fintech", "Data Analytics", "Cybersecurity"],
        "summary": "Charlotte is the second-largest US banking center after New York, hosting Bank of America and Wells Fargo headquarters. This concentration of financial infrastructure drives strong demand for financial technology, risk analytics, and banking software — making it a strategic market for anyone targeting the finance sector.",
        "cost_of_living": {"index": 94, "note": "Below US average. Great for finance-tech careers without NYC price tag.", "avg_rent_1br": 1480, "avg_home_price": 370000},
        "weather": {"description": "Hot summers, mild winters. Occasional ice storms.", "avg_summer": "90°F (32°C)", "avg_winter": "42°F (6°C)", "sunny_days": 218},
        "colleges": ["UNC Charlotte", "Davidson College", "Queens University"],
        "major_companies": ["Bank of America (HQ)", "Wells Fargo Tech Hub", "Truist Financial", "Duke Energy", "AvidXchange"]
    },
    {
        "name": "Phoenix, AZ", "tech_score": 80, "growth_label": "Explosive",
        "total_tech_jobs": 5200, "ai_jobs": 840, "finance_tech_jobs": 1100,
        "avg_salary": 105000, "startup_activity": "High",
        "top_industries": ["Semiconductor Manufacturing", "Fintech", "Healthcare Tech", "Logistics"],
        "summary": "Phoenix is experiencing one of the largest manufacturing and tech investment surges of any US city, driven by TSMC's $40B semiconductor fab investment and Intel's expanded manufacturing presence. The city is positioning itself as a key node in the US domestic semiconductor supply chain.",
        "cost_of_living": {"index": 98, "note": "Near US average. Housing rising fast due to migration but still competitive.", "avg_rent_1br": 1550, "avg_home_price": 400000},
        "weather": {"description": "Very hot summers (extreme heat alerts). Mild, sunny winters.", "avg_summer": "104°F (40°C)", "avg_winter": "56°F (13°C)", "sunny_days": 299},
        "colleges": ["Arizona State University", "University of Arizona", "Grand Canyon University"],
        "major_companies": ["TSMC (fab)", "Intel", "PayPal", "GoDaddy", "Microchip Technology", "ON Semiconductor"]
    },
    {
        "name": "Pittsburgh, PA", "tech_score": 79, "growth_label": "Rising",
        "total_tech_jobs": 4100, "ai_jobs": 890, "finance_tech_jobs": 620,
        "avg_salary": 107000, "startup_activity": "High",
        "top_industries": ["AI & Robotics", "Autonomous Vehicles", "Healthcare AI", "Advanced Manufacturing"],
        "summary": "Pittsburgh punches well above its size in artificial intelligence and robotics, anchored by Carnegie Mellon University — consistently ranked the top AI research university in the world. Uber ATG, Waymo, and Aurora have all established autonomous vehicle research centers here, drawn by CMU's deep talent pipeline.",
        "cost_of_living": {"index": 88, "note": "Well below US average. One of the best value markets for tech talent.", "avg_rent_1br": 1200, "avg_home_price": 240000},
        "weather": {"description": "Cold snowy winters, warm summers. Overcast frequently in winter.", "avg_summer": "83°F (28°C)", "avg_winter": "32°F (0°C)", "sunny_days": 161},
        "colleges": ["Carnegie Mellon University", "University of Pittsburgh", "Duquesne University"],
        "major_companies": ["Google (AI lab)", "Uber ATG", "Aurora Innovation", "Duolingo", "Argo AI", "RE/MAX"]
    },
    {
        "name": "Nashville, TN", "tech_score": 78, "growth_label": "Rising",
        "total_tech_jobs": 3200, "ai_jobs": 620, "finance_tech_jobs": 590,
        "avg_salary": 98000, "startup_activity": "Medium",
        "top_industries": ["Healthcare Tech", "SaaS", "Logistics Tech", "Music Tech"],
        "summary": "Nashville is the healthcare technology capital of the United States, home to more healthcare companies per capita than any other US city. HCA Healthcare, one of the largest hospital operators globally, is headquartered here, driving strong demand for health informatics, medical software, and health data analytics talent.",
        "cost_of_living": {"index": 91, "note": "Below US average. No state income tax. Strong growth value.", "avg_rent_1br": 1620, "avg_home_price": 420000},
        "weather": {"description": "Hot summers, mild winters. Occasional ice storms.", "avg_summer": "90°F (32°C)", "avg_winter": "38°F (3°C)", "sunny_days": 208},
        "colleges": ["Vanderbilt University", "Belmont University", "Tennessee State University"],
        "major_companies": ["Amazon (hub)", "HCA Healthcare (HQ)", "AllianceBernstein", "Dollar General Tech"]
    },
    {
        "name": "Minneapolis, MN", "tech_score": 77, "growth_label": "Rising",
        "total_tech_jobs": 4300, "ai_jobs": 680, "finance_tech_jobs": 1200,
        "avg_salary": 113000, "startup_activity": "Medium",
        "top_industries": ["Medical Devices", "Financial Services Tech", "Retail Tech", "AgTech"],
        "summary": "Minneapolis is a quietly underrated tech hub with particular strength in medical devices — Medtronic, one of the world's largest medical technology companies, is headquartered here. The city also hosts significant financial services technology activity driven by US Bancorp and a growing retail tech sector from Target's technology division.",
        "cost_of_living": {"index": 97, "note": "Near US average. Good value for the tech salaries available.", "avg_rent_1br": 1380, "avg_home_price": 310000},
        "weather": {"description": "Very cold winters with significant snowfall. Warm summers. Extreme seasonal variation.", "avg_summer": "83°F (28°C)", "avg_winter": "16°F (-9°C)", "sunny_days": 198},
        "colleges": ["University of Minnesota", "Macalester College", "Carleton College"],
        "major_companies": ["Medtronic (HQ)", "Target (tech div)", "US Bancorp", "Best Buy", "3M", "Cargill"]
    },
    {
        "name": "Tampa, FL", "tech_score": 76, "growth_label": "Rising",
        "total_tech_jobs": 3600, "ai_jobs": 580, "finance_tech_jobs": 920,
        "avg_salary": 96000, "startup_activity": "Medium",
        "top_industries": ["Cybersecurity", "Healthcare IT", "Fintech", "Defense Tech"],
        "summary": "Tampa has emerged as a growing cybersecurity hub, partly due to proximity to MacDill Air Force Base and US Central Command. The region hosts a significant defense technology contractor ecosystem and is increasingly attracting financial services firms relocating from higher-cost Northeast markets.",
        "cost_of_living": {"index": 96, "note": "Slightly below US average. Rising quickly due to migration from Northeast.", "avg_rent_1br": 1720, "avg_home_price": 370000},
        "weather": {"description": "Hot humid summers with frequent afternoon thunderstorms. Warm mild winters.", "avg_summer": "91°F (33°C)", "avg_winter": "58°F (14°C)", "sunny_days": 233},
        "colleges": ["University of South Florida", "University of Tampa", "Hillsborough Community College"],
        "major_companies": ["Jabil", "WellCare Health", "Raymond James", "Citigroup (tech hub)", "ConnectWise"]
    },
    {
        "name": "Columbus, OH", "tech_score": 75, "growth_label": "Rising",
        "total_tech_jobs": 3400, "ai_jobs": 540, "finance_tech_jobs": 980,
        "avg_salary": 97000, "startup_activity": "Medium",
        "top_industries": ["Fintech", "Insurance Tech", "E-Commerce Tech", "Data Centers"],
        "summary": "Columbus benefits from Ohio State University's large engineering output and a growing financial services technology sector anchored by Nationwide Insurance and JPMorgan's significant operations presence. The city is also becoming a major data center hub due to its central location, reliable power, and lower land costs.",
        "cost_of_living": {"index": 86, "note": "Well below US average. Excellent value market with growing salaries.", "avg_rent_1br": 1150, "avg_home_price": 275000},
        "weather": {"description": "Cold winters with moderate snow. Warm humid summers.", "avg_summer": "84°F (29°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 177},
        "colleges": ["Ohio State University", "Columbus State Community College", "Capital University"],
        "major_companies": ["Nationwide (HQ)", "JPMorgan (major ops)", "AEP", "Limited Brands", "Root Insurance"]
    },
    {
        "name": "San Antonio, TX", "tech_score": 74, "growth_label": "Rising",
        "total_tech_jobs": 3100, "ai_jobs": 490, "finance_tech_jobs": 720,
        "avg_salary": 92000, "startup_activity": "Medium",
        "top_industries": ["Cybersecurity", "Military Tech", "Cloud Infrastructure", "Healthcare IT"],
        "summary": "San Antonio is the cybersecurity capital of the United States by some metrics, hosting the NSA's largest field office, US Army Cyber Command, and over 80 cybersecurity-focused companies. This military-driven demand has created a specialized talent pipeline and government contracting ecosystem unlike anywhere else.",
        "cost_of_living": {"index": 87, "note": "Below US average. No state income tax and affordable housing.", "avg_rent_1br": 1180, "avg_home_price": 280000},
        "weather": {"description": "Very hot summers, mild winters. Occasional brief freezes.", "avg_summer": "97°F (36°C)", "avg_winter": "50°F (10°C)", "sunny_days": 220},
        "colleges": ["UT San Antonio", "Trinity University", "St. Mary's University"],
        "major_companies": ["USAA (HQ)", "Rackspace (HQ)", "Valero Energy Tech", "H-E-B Digital", "iHeartMedia"]
    },
    {
        "name": "Indianapolis, IN", "tech_score": 73, "growth_label": "Emerging",
        "total_tech_jobs": 2900, "ai_jobs": 450, "finance_tech_jobs": 680,
        "avg_salary": 93000, "startup_activity": "Medium",
        "top_industries": ["Healthcare IT", "Logistics Tech", "Insurance Tech", "Life Sciences"],
        "summary": "Indianapolis is quietly becoming a significant healthcare IT hub, driven by Eli Lilly's global pharmaceutical headquarters and a dense network of hospital systems including IU Health. The city offers one of the best cost-to-compensation ratios in tech, making it attractive for companies looking to build engineering teams outside expensive coastal markets.",
        "cost_of_living": {"index": 84, "note": "Significantly below US average. Exceptional value for tech professionals.", "avg_rent_1br": 1050, "avg_home_price": 255000},
        "weather": {"description": "Cold snowy winters, warm humid summers. Significant seasonal variation.", "avg_summer": "84°F (29°C)", "avg_winter": "28°F (-2°C)", "sunny_days": 183},
        "colleges": ["Indiana University", "Purdue University (IUPUI)", "Butler University"],
        "major_companies": ["Eli Lilly (HQ)", "Salesforce (regional HQ)", "Angi", "Interactive Intelligence", "KSM"]
    },
    {
        "name": "Portland, OR", "tech_score": 72, "growth_label": "Emerging",
        "total_tech_jobs": 3200, "ai_jobs": 520, "finance_tech_jobs": 480,
        "avg_salary": 118000, "startup_activity": "Medium",
        "top_industries": ["Semiconductor Design", "Clean Tech", "SaaS", "Creative Tech"],
        "summary": "Portland hosts a significant but often overlooked semiconductor design cluster, anchored by Intel's largest global campus in Hillsboro. The city also has a growing clean technology sector, aligning with Oregon's progressive energy policy. The tech culture tends toward open-source and mission-driven startups.",
        "cost_of_living": {"index": 109, "note": "Above US average but lower than Seattle or SF.", "avg_rent_1br": 1750, "avg_home_price": 480000},
        "weather": {"description": "Mild and very rainy in winter. Warm, dry, and beautiful in summer.", "avg_summer": "80°F (27°C)", "avg_winter": "40°F (4°C)", "sunny_days": 144},
        "colleges": ["Oregon Health & Science University", "Portland State University", "Reed College"],
        "major_companies": ["Intel (largest campus)", "Nike (HQ)", "adidas North America", "Daimler Trucks", "Precision Castparts"]
    },
    {
        "name": "Kansas City, MO", "tech_score": 70, "growth_label": "Emerging",
        "total_tech_jobs": 2600, "ai_jobs": 400, "finance_tech_jobs": 620,
        "avg_salary": 90000, "startup_activity": "Medium",
        "top_industries": ["Logistics Tech", "AgTech", "Insurance Tech", "Smart City Infrastructure"],
        "summary": "Kansas City is positioning itself as a logistics and supply chain technology hub, leveraging its central US location and rail infrastructure. The city was one of the first in the nation to deploy citywide gigabit internet infrastructure and has attracted a growing number of smart city and IoT technology companies.",
        "cost_of_living": {"index": 83, "note": "Well below US average. One of the most affordable large metros in the US.", "avg_rent_1br": 1050, "avg_home_price": 250000},
        "weather": {"description": "Cold snowy winters, hot humid summers. Tornado risk in spring.", "avg_summer": "89°F (32°C)", "avg_winter": "29°F (-2°C)", "sunny_days": 193},
        "colleges": ["University of Missouri-Kansas City", "Kansas State University", "Rockhurst University"],
        "major_companies": ["Cerner (Oracle)", "Garmin (regional)", "Sprint (T-Mobile)", "H&R Block Tech", "VinSolutions"]
    },
    {
        "name": "Baltimore, MD", "tech_score": 69, "growth_label": "Emerging",
        "total_tech_jobs": 2800, "ai_jobs": 520, "finance_tech_jobs": 580,
        "avg_salary": 108000, "startup_activity": "Medium",
        "top_industries": ["Cybersecurity", "Government Tech", "Biotech", "Defense Tech"],
        "summary": "Baltimore benefits from its proximity to Washington DC and the NSA's Fort Meade campus, creating significant demand for cybersecurity and government technology contractors. Johns Hopkins University drives a strong biomedical research and health informatics ecosystem that is increasingly intersecting with AI and data science.",
        "cost_of_living": {"index": 98, "note": "Near US average. Good value given proximity to DC and strong federal salaries.", "avg_rent_1br": 1520, "avg_home_price": 310000},
        "weather": {"description": "Cold winters, hot humid summers. Mid-Atlantic climate with four seasons.", "avg_summer": "87°F (31°C)", "avg_winter": "34°F (1°C)", "sunny_days": 205},
        "colleges": ["Johns Hopkins University", "University of Maryland", "Towson University"],
        "major_companies": ["Leidos", "Northrop Grumman", "T. Rowe Price", "Under Armour Tech", "Medifast"]
    },
    {
        "name": "Detroit, MI", "tech_score": 68, "growth_label": "Emerging",
        "total_tech_jobs": 2500, "ai_jobs": 480, "finance_tech_jobs": 420,
        "avg_salary": 95000, "startup_activity": "Medium",
        "top_industries": ["Automotive Tech", "Autonomous Vehicles", "Manufacturing AI", "Mobility Tech"],
        "summary": "Detroit is undergoing a significant technology transformation driven by the automotive industry's shift toward electric vehicles and autonomous driving systems. Ford, GM, and Stellantis are all investing heavily in software engineering and AI talent, creating a new category of automotive-tech roles that combine traditional manufacturing expertise with modern software development.",
        "cost_of_living": {"index": 82, "note": "Below US average. City revitalization ongoing — housing very affordable.", "avg_rent_1br": 1050, "avg_home_price": 210000},
        "weather": {"description": "Very cold snowy winters, warm summers. Lake effect snow from Lake Erie.", "avg_summer": "82°F (28°C)", "avg_winter": "25°F (-4°C)", "sunny_days": 160},
        "colleges": ["University of Michigan", "Michigan State University", "Wayne State University"],
        "major_companies": ["Ford (tech div)", "GM (tech div)", "Stellantis", "Quicken Loans (Rocket)", "Lear Corporation"]
    },
    {
        "name": "Orlando, FL", "tech_score": 67, "growth_label": "Emerging",
        "total_tech_jobs": 2400, "ai_jobs": 420, "finance_tech_jobs": 380,
        "avg_salary": 89000, "startup_activity": "Medium",
        "top_industries": ["Simulation Tech", "Defense & Aerospace", "Hospitality Tech", "Gaming"],
        "summary": "Orlando hosts one of the world's most concentrated simulation and modeling technology clusters, driven by contracts with the US military's training and simulation programs based at the Army's Program Executive Office for Simulation, Training and Instrumentation. The gaming and esports sector is also growing significantly.",
        "cost_of_living": {"index": 94, "note": "Below US average. No state income tax. Rising due to migration.", "avg_rent_1br": 1650, "avg_home_price": 360000},
        "weather": {"description": "Hot and humid year-round. Afternoon thunderstorms common in summer. Hurricane risk.", "avg_summer": "91°F (33°C)", "avg_winter": "60°F (15°C)", "sunny_days": 233},
        "colleges": ["University of Central Florida (largest US enrollment)", "Full Sail University", "Valencia College"],
        "major_companies": ["Lockheed Martin (simulation)", "Northrop Grumman", "EA (studio)", "Electronic Arts", "CNL Financial"]
    },
    {
        "name": "Richmond, VA", "tech_score": 65, "growth_label": "Emerging",
        "total_tech_jobs": 1900, "ai_jobs": 310, "finance_tech_jobs": 480,
        "avg_salary": 92000, "startup_activity": "Low",
        "top_industries": ["Government Tech", "Cybersecurity", "Financial Services Tech", "Data Centers"],
        "summary": "Richmond is an emerging market benefiting from Virginia's dominant position in US data center infrastructure — Northern Virginia hosts more data center capacity than anywhere else on Earth, and Richmond is increasingly part of this corridor. The city also has growing government technology and financial services activity.",
        "cost_of_living": {"index": 91, "note": "Below US average. Good value with access to DC and Northern Virginia markets.", "avg_rent_1br": 1280, "avg_home_price": 330000},
        "weather": {"description": "Mild four seasons. Hot humid summers, cold winters with occasional snow.", "avg_summer": "88°F (31°C)", "avg_winter": "35°F (2°C)", "sunny_days": 205},
        "colleges": ["Virginia Commonwealth University", "University of Richmond", "Virginia Union University"],
        "major_companies": ["Capital One (nearby)", "Dominion Energy Tech", "CarMax Digital", "Markel", "Altria Group"]
    },
    {
        "name": "San Francisco, CA", "tech_score": 98, "growth_label": "Strong",
        "total_tech_jobs": 28000, "ai_jobs": 6200, "finance_tech_jobs": 3800,
        "avg_salary": 172000, "startup_activity": "Very High",
        "top_industries": ["AI & Machine Learning", "Cloud Computing", "Venture Capital", "Crypto & Web3"],
        "summary": "San Francisco and Silicon Valley remain the undisputed global capital of technology. Despite post-pandemic exodus, the Bay Area retains the highest concentration of AI research labs, venture capital, and unicorn startups on the planet. OpenAI, Anthropic, Stripe, and hundreds of AI-native companies are headquartered here.",
        "cost_of_living": {"index": 180, "note": "One of the most expensive cities in the world. High salaries are necessary just to break even.", "avg_rent_1br": 3400, "avg_home_price": 1200000},
        "weather": {"description": "Mild year-round. Famously foggy summers. Rarely hot or cold.", "avg_summer": "65°F (18°C)", "avg_winter": "52°F (11°C)", "sunny_days": 259},
        "colleges": ["Stanford University", "UC Berkeley", "UCSF", "UC San Francisco"],
        "major_companies": ["OpenAI", "Anthropic", "Stripe", "Salesforce", "Uber", "Lyft", "Airbnb", "Cloudflare"]
    },
    {
        "name": "New York, NY", "tech_score": 97, "growth_label": "Strong",
        "total_tech_jobs": 32000, "ai_jobs": 5800, "finance_tech_jobs": 8400,
        "avg_salary": 162000, "startup_activity": "Very High",
        "top_industries": ["Fintech", "AdTech", "AI & Machine Learning", "Media Tech"],
        "summary": "New York City is the second-largest tech ecosystem in the US and the world's largest fintech hub. The city's density of financial institutions, media companies, and Fortune 500 headquarters drives massive demand for software engineers, data scientists, and AI talent. NYC's tech scene is increasingly producing AI-native startups.",
        "cost_of_living": {"index": 168, "note": "Extremely expensive. Among the highest costs in the US outside of SF.", "avg_rent_1br": 3200, "avg_home_price": 950000},
        "weather": {"description": "Four distinct seasons. Cold snowy winters, hot humid summers.", "avg_summer": "85°F (29°C)", "avg_winter": "34°F (1°C)", "sunny_days": 224},
        "colleges": ["Columbia University", "NYU", "Cornell Tech", "City University of New York"],
        "major_companies": ["Google (HQ2)", "Amazon (HQ2)", "Bloomberg", "IBM", "Spotify", "Etsy", "MongoDB", "Datadog"]
    },
    {
        "name": "Los Angeles, CA", "tech_score": 89, "growth_label": "Strong",
        "total_tech_jobs": 16000, "ai_jobs": 3100, "finance_tech_jobs": 2100,
        "avg_salary": 144000, "startup_activity": "Very High",
        "top_industries": ["Entertainment Tech", "AI & Creative Tools", "E-Commerce", "Aerospace Tech"],
        "summary": "Los Angeles has evolved into a powerhouse tech market, anchored by the intersection of entertainment and technology. SpaceX, Snap, and a growing number of AI creative tool companies have established LA as a major tech hub distinct from Silicon Valley. The city leads the nation in creator economy and entertainment technology.",
        "cost_of_living": {"index": 145, "note": "Very expensive. Lower than SF but still among the top 5 most expensive US cities.", "avg_rent_1br": 2600, "avg_home_price": 850000},
        "weather": {"description": "Warm and sunny almost year-round. Mild winters, warm summers. Low humidity.", "avg_summer": "84°F (29°C)", "avg_winter": "58°F (14°C)", "sunny_days": 284},
        "colleges": ["UCLA", "USC", "Caltech", "LMU"],
        "major_companies": ["SpaceX", "Snap", "Hulu", "Riot Games", "TikTok (US HQ)", "Honey", "ServiceTitan"]
    },
    {
        "name": "Washington, DC", "tech_score": 84, "growth_label": "Strong",
        "total_tech_jobs": 12000, "ai_jobs": 2400, "finance_tech_jobs": 1800,
        "avg_salary": 138000, "startup_activity": "High",
        "top_industries": ["Government Tech", "Cybersecurity", "Defense Tech", "Cloud Infrastructure"],
        "summary": "Washington DC and Northern Virginia form the world's largest government technology market. Amazon Web Services is headquartered in nearby Arlington, and the region hosts more federal technology contracts than any other metro area. The cybersecurity sector is particularly dominant, fueled by NSA, DHS, and defense contractors.",
        "cost_of_living": {"index": 130, "note": "Significantly above US average. Northern Virginia slightly cheaper than DC proper.", "avg_rent_1br": 2400, "avg_home_price": 620000},
        "weather": {"description": "Four seasons. Hot humid summers, cold winters with occasional snow.", "avg_summer": "88°F (31°C)", "avg_winter": "35°F (2°C)", "sunny_days": 202},
        "colleges": ["Georgetown University", "George Mason University", "American University", "George Washington University"],
        "major_companies": ["Amazon Web Services (HQ)", "Booz Allen Hamilton", "SAIC", "Leidos", "Palantir", "Microsoft (federal)"]
    },
    {
        "name": "San Diego, CA", "tech_score": 82, "growth_label": "Rising",
        "total_tech_jobs": 8200, "ai_jobs": 1600, "finance_tech_jobs": 980,
        "avg_salary": 130000, "startup_activity": "High",
        "top_industries": ["Biotech & Life Sciences", "Defense Tech", "Semiconductor Design", "Wireless Tech"],
        "summary": "San Diego is one of the most specialized tech markets in the US, with world-class strength in biotech and wireless technology. Qualcomm's global headquarters anchors a major semiconductor and wireless ecosystem, while proximity to major research universities and the military drives strong biotech and defense technology clusters.",
        "cost_of_living": {"index": 138, "note": "Very expensive. Rising faster than most West Coast cities.", "avg_rent_1br": 2500, "avg_home_price": 820000},
        "weather": {"description": "Near-perfect climate year-round. Mild temperatures, low humidity, rarely extreme.", "avg_summer": "76°F (24°C)", "avg_winter": "58°F (14°C)", "sunny_days": 266},
        "colleges": ["UC San Diego", "San Diego State University", "USD"],
        "major_companies": ["Qualcomm (HQ)", "ServiceNow", "Illumina", "Verizon Wireless (R&D)", "Northrop Grumman"]
    },
    {
        "name": "Houston, TX", "tech_score": 78, "growth_label": "Rising",
        "total_tech_jobs": 7400, "ai_jobs": 1200, "finance_tech_jobs": 1100,
        "avg_salary": 112000, "startup_activity": "High",
        "top_industries": ["Energy Tech", "Healthcare IT", "Aerospace", "Cybersecurity"],
        "summary": "Houston is the global center of energy technology, home to NASA's Johnson Space Center and the largest concentration of energy companies in the world. The city's healthcare sector — anchored by the Texas Medical Center, the world's largest medical complex — is driving rapid growth in health informatics and medical AI.",
        "cost_of_living": {"index": 95, "note": "Below US average. No state income tax. Good value for a major metro.", "avg_rent_1br": 1420, "avg_home_price": 330000},
        "weather": {"description": "Very hot and humid summers. Mild winters. Hurricane risk. Frequent flooding.", "avg_summer": "94°F (34°C)", "avg_winter": "52°F (11°C)", "sunny_days": 204},
        "colleges": ["Rice University", "University of Houston", "Texas Southern University"],
        "major_companies": ["NASA Johnson Space Center", "Schlumberger", "HP Enterprise", "NRG Energy", "CenterPoint"]
    },
    {
        "name": "Philadelphia, PA", "tech_score": 76, "growth_label": "Rising",
        "total_tech_jobs": 6800, "ai_jobs": 1300, "finance_tech_jobs": 1400,
        "avg_salary": 118000, "startup_activity": "Medium",
        "top_industries": ["Biotech & Pharma", "Healthcare IT", "Fintech", "EdTech"],
        "summary": "Philadelphia anchors a biotech and pharmaceutical corridor stretching from the city to Princeton, NJ. The region hosts a dense cluster of pharmaceutical giants including GSK and Merck, driving strong demand for bioinformatics and healthcare data talent. Penn's medical school and CHOP generate significant health AI research.",
        "cost_of_living": {"index": 110, "note": "Above US average but significantly cheaper than NYC or DC.", "avg_rent_1br": 1850, "avg_home_price": 350000},
        "weather": {"description": "Four seasons. Hot humid summers, cold winters with snow.", "avg_summer": "86°F (30°C)", "avg_winter": "32°F (0°C)", "sunny_days": 207},
        "colleges": ["University of Pennsylvania", "Temple University", "Drexel University", "Jefferson University"],
        "major_companies": ["Comcast (HQ)", "GSK (US HQ)", "Merck (nearby)", "Day & Zimmermann", "SEI Investments"]
    },
    {
        "name": "St. Louis, MO", "tech_score": 64, "growth_label": "Emerging",
        "total_tech_jobs": 3100, "ai_jobs": 480, "finance_tech_jobs": 720,
        "avg_salary": 94000, "startup_activity": "Medium",
        "top_industries": ["Healthcare IT", "AgTech", "Logistics Tech", "Fintech"],
        "summary": "St. Louis is a quietly growing tech market with particular strength in healthcare IT and agricultural technology, benefiting from Washington University's medical research output and proximity to major agribusiness companies. The city's low cost of living makes it attractive for companies building engineering teams outside coastal markets.",
        "cost_of_living": {"index": 82, "note": "Well below US average. One of the most affordable major metros in the US.", "avg_rent_1br": 1100, "avg_home_price": 230000},
        "weather": {"description": "Hot humid summers, cold winters with moderate snow. Tornado risk in spring.", "avg_summer": "88°F (31°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 191},
        "colleges": ["Washington University in St. Louis", "Saint Louis University", "Missouri S&T"],
        "major_companies": ["Edward Jones", "Centene", "Emerson Electric", "Peabody Energy", "Bayer Crop Science"]
    },
    {
        "name": "Cincinnati, OH", "tech_score": 63, "growth_label": "Emerging",
        "total_tech_jobs": 2800, "ai_jobs": 440, "finance_tech_jobs": 680,
        "avg_salary": 92000, "startup_activity": "Medium",
        "top_industries": ["CPG Tech", "Logistics Tech", "Insurance Tech", "Healthcare IT"],
        "summary": "Cincinnati is home to an unusual concentration of consumer goods technology, driven by Procter & Gamble's global headquarters and its heavy investment in data science and digital marketing. The city is also building a logistics technology cluster around its position as a major inland distribution hub.",
        "cost_of_living": {"index": 84, "note": "Well below US average. Excellent value for tech salaries.", "avg_rent_1br": 1080, "avg_home_price": 240000},
        "weather": {"description": "Cold winters with moderate snow, hot humid summers.", "avg_summer": "86°F (30°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 178},
        "colleges": ["University of Cincinnati", "Xavier University", "Miami University"],
        "major_companies": ["Procter & Gamble (HQ)", "Kroger (HQ)", "Fifth Third Bank", "Great American Insurance", "Luxottica"]
    },
    {
        "name": "Sacramento, CA", "tech_score": 62, "growth_label": "Emerging",
        "total_tech_jobs": 2900, "ai_jobs": 460, "finance_tech_jobs": 520,
        "avg_salary": 102000, "startup_activity": "Medium",
        "top_industries": ["Government Tech", "Clean Energy Tech", "AgTech", "Healthcare IT"],
        "summary": "Sacramento benefits from its role as California's capital, creating steady demand for government technology and digital services contractors. The city is also becoming a clean energy technology hub, aligned with California's aggressive renewable energy mandates and proximity to Silicon Valley talent spillover.",
        "cost_of_living": {"index": 112, "note": "Above US average but significantly cheaper than Bay Area. Many SF workers have relocated here.", "avg_rent_1br": 1680, "avg_home_price": 480000},
        "weather": {"description": "Hot dry summers, mild wet winters. Excellent sunshine.", "avg_summer": "95°F (35°C)", "avg_winter": "46°F (8°C)", "sunny_days": 269},
        "colleges": ["UC Davis", "Sacramento State", "Sac City College"],
        "major_companies": ["Apple (data center)", "Intel (fab)", "VSP Global", "SAFE Credit Union", "Sutter Health"]
    },
    {
        "name": "Cleveland, OH", "tech_score": 61, "growth_label": "Emerging",
        "total_tech_jobs": 2600, "ai_jobs": 420, "finance_tech_jobs": 560,
        "avg_salary": 90000, "startup_activity": "Medium",
        "top_industries": ["Healthcare AI", "Advanced Manufacturing", "Biomedical Tech", "Fintech"],
        "summary": "Cleveland is positioning itself as a healthcare AI and biomedical technology hub, anchored by the Cleveland Clinic — consistently ranked among the top hospitals in the world — and Case Western Reserve University. The city's advanced manufacturing heritage is transitioning into smart manufacturing and industrial AI.",
        "cost_of_living": {"index": 80, "note": "Significantly below US average. One of the most affordable metros in the country.", "avg_rent_1br": 1020, "avg_home_price": 195000},
        "weather": {"description": "Very cold winters with heavy lake-effect snow. Warm summers. Overcast frequently.", "avg_summer": "81°F (27°C)", "avg_winter": "26°F (-3°C)", "sunny_days": 166},
        "colleges": ["Case Western Reserve University", "Cleveland State University", "John Carroll University"],
        "major_companies": ["Cleveland Clinic (tech div)", "Progressive Insurance (HQ)", "KeyBank", "Sherwin-Williams", "Parker Hannifin"]
    },
    {
        "name": "Oklahoma City, OK", "tech_score": 59, "growth_label": "Emerging",
        "total_tech_jobs": 2200, "ai_jobs": 340, "finance_tech_jobs": 480,
        "avg_salary": 86000, "startup_activity": "Low",
        "top_industries": ["Energy Tech", "Aerospace", "Healthcare IT", "AgTech"],
        "summary": "Oklahoma City is an underrated tech market with significant aerospace and energy technology activity, anchored by Tinker Air Force Base and a cluster of oil and gas technology companies. The city offers exceptional value for tech talent, with some of the lowest costs of living among US metros with active tech sectors.",
        "cost_of_living": {"index": 78, "note": "Well below US average. Among the most affordable large metros in the US.", "avg_rent_1br": 950, "avg_home_price": 210000},
        "weather": {"description": "Hot summers, mild winters. Significant tornado risk in spring. Severe weather common.", "avg_summer": "94°F (34°C)", "avg_winter": "37°F (3°C)", "sunny_days": 223},
        "colleges": ["University of Oklahoma", "Oklahoma State University", "University of Central Oklahoma"],
        "major_companies": ["Devon Energy", "Paycom (HQ)", "Loves Travel Stops (tech)", "INTEGRIS Health", "Tinker AFB"]
    },
    {
        "name": "Omaha, NE", "tech_score": 58, "growth_label": "Emerging",
        "total_tech_jobs": 2100, "ai_jobs": 320, "finance_tech_jobs": 580,
        "avg_salary": 88000, "startup_activity": "Low",
        "top_industries": ["Insurance Tech", "Fintech", "Telecom", "Data Centers"],
        "summary": "Omaha is a quiet but stable tech market anchored by a surprisingly large financial services and insurance technology sector. Berkshire Hathaway's headquarters drives a significant fintech and insurance analytics ecosystem, and the city's central location makes it a major data center hub for latency-sensitive applications.",
        "cost_of_living": {"index": 79, "note": "Among the most affordable major metros. Excellent value for financial tech careers.", "avg_rent_1br": 980, "avg_home_price": 225000},
        "weather": {"description": "Cold snowy winters, hot humid summers. Tornado risk in spring.", "avg_summer": "88°F (31°C)", "avg_winter": "22°F (-5°C)", "sunny_days": 195},
        "colleges": ["University of Nebraska Omaha", "Creighton University", "Bellevue University"],
        "major_companies": ["Berkshire Hathaway (HQ)", "Union Pacific (HQ)", "TD Ameritrade (Schwab)", "First Data", "Mutual of Omaha"]
    },
    {
        "name": "Milwaukee, WI", "tech_score": 57, "growth_label": "Emerging",
        "total_tech_jobs": 2000, "ai_jobs": 300, "finance_tech_jobs": 440,
        "avg_salary": 87000, "startup_activity": "Low",
        "top_industries": ["Manufacturing Tech", "Water Tech", "Healthcare IT", "Supply Chain Tech"],
        "summary": "Milwaukee is developing a niche in water technology — the city has branded itself as the 'Water Tech Capital of the World,' with a cluster of water treatment, analytics, and infrastructure companies. The city also has growing industrial IoT and smart manufacturing activity driven by its deep manufacturing heritage.",
        "cost_of_living": {"index": 85, "note": "Below US average. Affordable housing and good quality of life.", "avg_rent_1br": 1120, "avg_home_price": 245000},
        "weather": {"description": "Very cold winters with heavy snow. Warm summers. Lake Michigan moderates temperatures.", "avg_summer": "81°F (27°C)", "avg_winter": "22°F (-5°C)", "sunny_days": 188},
        "colleges": ["University of Wisconsin-Milwaukee", "Marquette University", "MSOE"],
        "major_companies": ["Johnson Controls (HQ)", "Northwestern Mutual (HQ)", "Rockwell Automation", "Harley-Davidson (tech)", "Rite-Hite"]
    },
    {
        "name": "New Orleans, LA", "tech_score": 55, "growth_label": "Emerging",
        "total_tech_jobs": 1800, "ai_jobs": 280, "finance_tech_jobs": 320,
        "avg_salary": 84000, "startup_activity": "Low",
        "top_industries": ["Energy Tech", "Healthcare IT", "Tourism Tech", "Logistics"],
        "summary": "New Orleans is an emerging tech market benefiting from post-Katrina investment in digital infrastructure and a growing startup community centered in the BioDistrict and along the St. Charles corridor. The city's port position drives logistics technology activity, and Tulane's research programs are building a life sciences tech pipeline.",
        "cost_of_living": {"index": 88, "note": "Below US average. Rising due to tech migration but still affordable.", "avg_rent_1br": 1280, "avg_home_price": 280000},
        "weather": {"description": "Subtropical. Very hot humid summers. Mild winters. Hurricane risk June-November.", "avg_summer": "91°F (33°C)", "avg_winter": "54°F (12°C)", "sunny_days": 216},
        "colleges": ["Tulane University", "Loyola University", "Xavier University of Louisiana"],
        "major_companies": ["Entergy (HQ)", "Pan-American Life", "Stone Pigman", "Waitr (DoorDash)", "Lucid"]
    },
    {
        "name": "Boise, ID", "tech_score": 54, "growth_label": "Rising",
        "total_tech_jobs": 1900, "ai_jobs": 290, "finance_tech_jobs": 280,
        "avg_salary": 92000, "startup_activity": "Medium",
        "top_industries": ["Semiconductor Manufacturing", "SaaS", "Healthcare IT", "Clean Energy"],
        "summary": "Boise has emerged as one of the fastest-growing tech markets in the Mountain West, driven by significant semiconductor manufacturing investment from Micron Technology and a growing SaaS startup community. The city consistently ranks among the top small metro areas for quality of life, attracting remote workers and startups from higher-cost markets.",
        "cost_of_living": {"index": 96, "note": "Near US average. Has risen significantly over 5 years due to migration from CA.", "avg_rent_1br": 1420, "avg_home_price": 430000},
        "weather": {"description": "High desert climate. Hot dry summers, cold winters with moderate snow.", "avg_summer": "94°F (34°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 206},
        "colleges": ["Boise State University", "University of Idaho", "College of Western Idaho"],
        "major_companies": ["Micron Technology (HQ)", "Hewlett Packard (campus)", "Clearwater Analytics", "Bodybuilding.com", "Lamb Weston"]
    },
    {
        "name": "Louisville, KY", "tech_score": 53, "growth_label": "Emerging",
        "total_tech_jobs": 1700, "ai_jobs": 260, "finance_tech_jobs": 340,
        "avg_salary": 85000, "startup_activity": "Low",
        "top_industries": ["Healthcare IT", "Logistics Tech", "Manufacturing Tech", "InsurTech"],
        "summary": "Louisville is building a healthcare IT cluster around its significant hospital system presence, including Humana's global headquarters — one of the largest health insurance companies in the US. The city's UPS WorldPort hub, the world's largest automated package sorting facility, is driving logistics technology and supply chain AI investment.",
        "cost_of_living": {"index": 82, "note": "Well below US average. Affordable housing with a growing tech job market.", "avg_rent_1br": 1050, "avg_home_price": 240000},
        "weather": {"description": "Four seasons. Hot humid summers, cold winters with occasional ice storms.", "avg_summer": "87°F (31°C)", "avg_winter": "35°F (2°C)", "sunny_days": 197},
        "colleges": ["University of Louisville", "Bellarmine University", "Spalding University"],
        "major_companies": ["Humana (HQ)", "UPS WorldPort (hub)", "Kindred Healthcare", "Tempur Sealy", "Yum! Brands"]
    },
    {
        "name": "Hartford, CT", "tech_score": 52, "growth_label": "Emerging",
        "total_tech_jobs": 1800, "ai_jobs": 280, "finance_tech_jobs": 520,
        "avg_salary": 104000, "startup_activity": "Low",
        "top_industries": ["Insurance Tech", "Financial Services Tech", "Defense Tech", "Healthcare IT"],
        "summary": "Hartford is the insurance capital of the United States, home to more insurance company headquarters per capita than any other city. This concentration of Aetna, The Hartford, and Travelers drives strong demand for actuarial technology, insurtech, and financial data analytics talent, making it a niche but stable market.",
        "cost_of_living": {"index": 108, "note": "Above US average. Lower than NYC/Boston but taxes are high.", "avg_rent_1br": 1580, "avg_home_price": 280000},
        "weather": {"description": "Cold snowy winters, warm summers. Classic New England four seasons.", "avg_summer": "84°F (29°C)", "avg_winter": "27°F (-3°C)", "sunny_days": 200},
        "colleges": ["University of Connecticut", "Trinity College", "University of Hartford"],
        "major_companies": ["The Hartford (HQ)", "Aetna (CVS)", "Travelers (HQ)", "United Technologies", "Cigna (nearby)"]
    },
    {
        "name": "Albuquerque, NM", "tech_score": 50, "growth_label": "Emerging",
        "total_tech_jobs": 1600, "ai_jobs": 240, "finance_tech_jobs": 220,
        "avg_salary": 86000, "startup_activity": "Low",
        "top_industries": ["Defense Tech", "National Labs Research", "Semiconductor", "Cybersecurity"],
        "summary": "Albuquerque is home to Sandia National Laboratories and Kirtland Air Force Base, creating a specialized defense technology and national security research ecosystem. The city has one of the highest concentrations of PhD-level researchers outside of major university towns, driven by DOE and DOD lab investment.",
        "cost_of_living": {"index": 84, "note": "Below US average. Very affordable for the tech talent available.", "avg_rent_1br": 1080, "avg_home_price": 280000},
        "weather": {"description": "High desert. Warm sunny days year-round. Low humidity. Cold nights. Mild winters.", "avg_summer": "92°F (33°C)", "avg_winter": "35°F (2°C)", "sunny_days": 310},
        "colleges": ["University of New Mexico", "New Mexico State University", "CNM"],
        "major_companies": ["Sandia National Laboratories", "Kirtland AFB", "Intel (fab)", "Presbyterian Healthcare", "Nusenda Credit Union"]
    },
    {
        "name": "Reno, NV", "tech_score": 48, "growth_label": "Rising",
        "total_tech_jobs": 1500, "ai_jobs": 220, "finance_tech_jobs": 200,
        "avg_salary": 90000, "startup_activity": "Medium",
        "top_industries": ["Data Centers", "Clean Energy Tech", "Logistics", "Manufacturing Tech"],
        "summary": "Reno has transformed from a casino town into a significant data center and advanced manufacturing hub, driven by Tesla's Gigafactory and major data center investments from Apple, Google, and Switch. Nevada's no-income-tax environment and proximity to California have made it attractive for companies and workers seeking lower costs.",
        "cost_of_living": {"index": 101, "note": "Near US average. Has risen significantly due to California migration.", "avg_rent_1br": 1520, "avg_home_price": 470000},
        "weather": {"description": "High desert. Sunny and dry year-round. Cold winters, warm summers. Low humidity.", "avg_summer": "93°F (34°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 252},
        "colleges": ["University of Nevada Reno", "Truckee Meadows Community College"],
        "major_companies": ["Tesla (Gigafactory)", "Apple (data center)", "Google (data center)", "Switch", "Panasonic"]
    },
    {
        "name": "Buffalo, NY", "tech_score": 47, "growth_label": "Emerging",
        "total_tech_jobs": 1400, "ai_jobs": 210, "finance_tech_jobs": 310,
        "avg_salary": 85000, "startup_activity": "Low",
        "top_industries": ["Advanced Manufacturing", "Healthcare IT", "Financial Services Tech", "Clean Energy"],
        "summary": "Buffalo is undergoing a gradual tech transformation, anchored by the University at Buffalo and significant investment in advanced manufacturing through the Buffalo Niagara Medical Campus. The city benefits from proximity to Canada and Niagara's clean hydroelectric power, making it attractive for data centers and clean tech companies.",
        "cost_of_living": {"index": 78, "note": "Well below US average. One of the most affordable mid-size cities in the Northeast.", "avg_rent_1br": 980, "avg_home_price": 185000},
        "weather": {"description": "Extremely cold winters with very heavy lake-effect snow. Warm short summers.", "avg_summer": "79°F (26°C)", "avg_winter": "24°F (-4°C)", "sunny_days": 160},
        "colleges": ["University at Buffalo", "Canisius University", "Daemen University"],
        "major_companies": ["M&T Bank (HQ)", "Delaware North (HQ)", "Moog Inc.", "Rich Products", "Independent Health"]
    },
    {
        "name": "Des Moines, IA", "tech_score": 45, "growth_label": "Emerging",
        "total_tech_jobs": 1300, "ai_jobs": 190, "finance_tech_jobs": 420,
        "avg_salary": 84000, "startup_activity": "Low",
        "top_industries": ["Insurance Tech", "AgTech", "Financial Services Tech", "Data Centers"],
        "summary": "Des Moines is the insurance technology capital of the Midwest, home to Principal Financial, Nationwide, and EMC Insurance. The city is also one of the nation's fastest-growing data center markets due to its low land costs, reliable power grid, and central location. Microsoft, Google, and Facebook all operate major data centers here.",
        "cost_of_living": {"index": 80, "note": "Well below US average. Exceptional value with competitive tech salaries.", "avg_rent_1br": 1020, "avg_home_price": 235000},
        "weather": {"description": "Cold snowy winters, hot humid summers. Tornado risk in spring.", "avg_summer": "86°F (30°C)", "avg_winter": "20°F (-7°C)", "sunny_days": 197},
        "colleges": ["Iowa State University", "Drake University", "Grand View University"],
        "major_companies": ["Principal Financial (HQ)", "Nationwide (regional)", "Microsoft (data center)", "Meta (data center)", "EMC Insurance"]
    },
    {
        "name": "El Paso, TX", "tech_score": 43, "growth_label": "Emerging",
        "total_tech_jobs": 1100, "ai_jobs": 160, "finance_tech_jobs": 180,
        "avg_salary": 72000, "startup_activity": "Low",
        "top_industries": ["Defense Tech", "Healthcare IT", "Cross-Border Commerce Tech", "Manufacturing Tech"],
        "summary": "El Paso's tech sector is shaped by Fort Bliss — one of the largest US Army installations — driving defense technology and cybersecurity demand. The city's position on the US-Mexico border creates unique opportunities in cross-border commerce technology, supply chain management, and bilingual customer service platforms.",
        "cost_of_living": {"index": 75, "note": "Among the most affordable large metros in the US. Very low housing costs.", "avg_rent_1br": 880, "avg_home_price": 195000},
        "weather": {"description": "Desert climate. Very sunny, hot dry summers, mild winters. Low humidity.", "avg_summer": "96°F (36°C)", "avg_winter": "42°F (6°C)", "sunny_days": 297},
        "colleges": ["UT El Paso", "El Paso Community College", "Western Texas College"],
        "major_companies": ["Fort Bliss (tech contracts)", "El Paso Electric", "Western Refining", "Alorica", "Convergys"]
    },
    {
        "name": "Spokane, WA", "tech_score": 41, "growth_label": "Emerging",
        "total_tech_jobs": 980, "ai_jobs": 140, "finance_tech_jobs": 160,
        "avg_salary": 82000, "startup_activity": "Low",
        "top_industries": ["Healthcare IT", "AgTech", "Clean Energy", "Defense Tech"],
        "summary": "Spokane is a small but growing tech market in Eastern Washington, benefiting from Washington State's no-income-tax environment and significantly lower costs than Seattle. The city's healthcare sector, anchored by Providence Health and MultiCare, is the primary tech employer, with clean energy and agricultural technology emerging as secondary clusters.",
        "cost_of_living": {"index": 88, "note": "Below US average. Much more affordable than Seattle while still in Washington state.", "avg_rent_1br": 1180, "avg_home_price": 310000},
        "weather": {"description": "Four distinct seasons. Cold snowy winters, warm dry summers. Less rain than Seattle.", "avg_summer": "84°F (29°C)", "avg_winter": "30°F (-1°C)", "sunny_days": 171},
        "colleges": ["Washington State University", "Gonzaga University", "Eastern Washington University"],
        "major_companies": ["Providence Health (tech)", "Avista Utilities", "Clearwater Paper", "STCU", "Itron"]
    },
    {
        "name": "Chattanooga, TN", "tech_score": 39, "growth_label": "Emerging",
        "total_tech_jobs": 820, "ai_jobs": 110, "finance_tech_jobs": 140,
        "avg_salary": 78000, "startup_activity": "Low",
        "top_industries": ["Logistics Tech", "Smart City Infrastructure", "Insurance Tech", "Manufacturing Tech"],
        "summary": "Chattanooga gained national attention as the first US city to deploy citywide gigabit fiber internet, earning it the nickname 'Gig City.' This infrastructure investment has attracted a small but growing startup community focused on smart city technology and logistics. The city's position as a major rail and trucking hub drives supply chain tech activity.",
        "cost_of_living": {"index": 83, "note": "Below US average. One of the more affordable Southeast cities.", "avg_rent_1br": 1150, "avg_home_price": 280000},
        "weather": {"description": "Four seasons. Hot humid summers, mild winters. Occasional ice storms.", "avg_summer": "89°F (32°C)", "avg_winter": "39°F (4°C)", "sunny_days": 204},
        "colleges": ["University of Tennessee at Chattanooga", "Chattanooga State", "Bryan College"],
        "major_companies": ["Unum Group (HQ)", "BlueCross BlueShield of TN", "Tennessee Valley Authority", "Volkswagen (plant tech)", "Amazon (fulfillment tech)"]
    },
]


@router.get("/cities")
def get_cities():
    return sorted(CITY_DATA, key=lambda x: x["tech_score"], reverse=True)
